---
- name: create deployment directory
  file:
    path: "{{ deployment_path }}"
    state: directory
    mode: 0755

- name: Download kolla-ansible from github
  git:
    repo: "{{ kolla_ansible_git_url }}"
    dest: "{{ kolla_ansible_git_path }}"
    version: "{{ kolla_ansible_git_version }}"
    force: yes

- name: check whether python2 is installed
  shell: which python2
  register: check_python2

- name: install required python modules
  pip:
    requirements: requirements.txt
    chdir: "{{ kolla_ansible_git_path }}"

- name: install kolla-ansible
  shell: python2 setup.py install
  args:
    chdir: "{{ kolla_ansible_git_path }}"
  when: check_python2.rc == 0
