---
- name: install python modules for docker
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
    - { "name": "docker-pycreds", "version": 0.2.2 }
    - { "name": "docker-py", "version": 1.10.6 }

#- name: deploy docker registry on local deploy server
#  docker_container:
#    name: registry
#    image: registry:2
#    state: started
#    restart_policy: always
#    ports:
#    - "{{ local_docker_registry_port }}:5000"
#    volumes:
#    - "registry:/var/lib/registry"
