---
# tasks file for openstack_db_backup
- name: create backup script
  template:
    src: openstack_db_backup.sh.j2
    dest: /etc/kolla/openstack_db_backup.sh

- name: create restore script
  template:
    src: openstack_db_store.sh.j2
    dest: /etc/kolla/openstack_db_restore.sh
