- name: install packages depanded
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libtool-ltdl

- name: install python modules for docker
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items:
  - { "name": "docker", "version": 2.7.0 }
  - { "name": "docker-pycreds", "version": 0.2.2 }
  when: inventory_hostname != "127.0.0.1"
